### ISSUE TITLE
AsyncIntegrationTests fails with Tomcat 8.5

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#75] opened 2016-03-23 13:30 UTC
It's an IllegalStateException from Tomcat but from debugging briefly it appears the `ServletHttpHandlerAdapter` is getting called twice. That's only happening in this test class though so something is different about it.

I'm creating a ticket here since we need to debug more and either narrow it down to an isolated test case or create something standalone (.war, .jar) that we can submit to Tomcat for debugging.

**Comment by rstoyanchev** [comment] 2016-03-23 14:46
https://github.com/rstoyanchev/spring-reactive/tree/tomcat-issue-repro

**Comment by poutsma** [comment] 2016-03-23 16:21
The following occurs after merging #74:

`mrt 23, 2016 5:16:26 PM org.apache.coyote.AbstractProtocol$ConnectionHandler process
SEVERE: Error reading request, ignored
java.lang.IllegalStateException: Calling [asyncOperation()] is not valid for a request with Async state [COMPLETING]
	at org.apache.coyote.AsyncStateMachine.asyncOperation(AsyncStateMachine.java:222)
	at org.apache.coyote.AbstractProcessor.dispatchNonBlockingRead(AbstractProcessor.java:233)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:197)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by poutsma** [comment] 2016-04-26 07:44
As of now, the only test that is failing under Tomcat 8.5 is the org.springframework.http.server.reactive.AsyncIntegrationTests, with the following stack trace:

```
apr 26, 2016 9:43:41 AM org.apache.coyote.AbstractProtocol$ConnectionHandler process
SEVERE: Error reading request, ignored
java.lang.IllegalStateException: Calling [asyncOperation()] is not valid for a request with Async state [COMPLETING]
	at org.apache.coyote.AsyncStateMachine.asyncOperation(AsyncStateMachine.java:222)
	at org.apache.coyote.AbstractProcessor.dispatchNonBlockingRead(AbstractProcessor.java:233)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:197)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

apr 26, 2016 9:43:41 AM org.apache.catalina.connector.CoyoteAdapter checkRecycled
INFO: Encountered a non-recycled request and recycled it forcedly.
org.apache.catalina.connector.CoyoteAdapter$RecycleRequiredException
	at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:479)
	at org.apache.coyote.http11.Http11Processor.recycle(Http11Processor.java:1826)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.release(AbstractProtocol.java:916)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

apr 26, 2016 9:43:42 AM org.apache.coyote.AbstractProtocol$ConnectionHandler process
SEVERE: Error reading request, ignored
java.lang.IllegalStateException: Calling [asyncOperation()] is not valid for a request with Async state [COMPLETING]
	at org.apache.coyote.AsyncStateMachine.asyncOperation(AsyncStateMachine.java:222)
	at org.apache.coyote.AbstractProcessor.dispatchNonBlockingRead(AbstractProcessor.java:233)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:197)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

apr 26, 2016 9:43:42 AM org.apache.catalina.connector.CoyoteAdapter checkRecycled
INFO: Encountered a non-recycled request and recycled it forcedly.
org.apache.catalina.connector.CoyoteAdapter$RecycleRequiredException
	at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:479)
	at org.apache.coyote.http11.Http11Processor.recycle(Http11Processor.java:1826)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.release(AbstractProtocol.java:916)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by markt-asf** [comment] 2016-05-05 08:24
Just a heads up that I have started to look at this. I have been able to recreate this with 8.5.x and 9.0.x but not with 8.0.x. That suggests the root cause lies somewhere in the connector refactoring  / clean-up that took place between 8.0.x and 8.5.x. This is currently top of my TODO list and I want to get it fixed before the next round of 9.0.x, 8.5.x and 8.0.x releases.

**Comment by markt-asf** [comment] 2016-05-05 09:27
Fixed in 8.5.x for 8.5.1 onwards and in 9.0.x for 9.0.0.M5 onwards. Both these releases should be out next week.

**Comment by poutsma** [comment] 2016-05-05 09:29
Great! Can you give us any insight as to what caused this? Just out of interest.

**Comment by markt-asf** [comment] 2016-05-05 09:40
Tomcat wasn't handling calls to AsyncContext.complete() correctly when made from a non-container thread when Non-Blocking IO was being used. Essentially, Tomcat assumed that the call to complete() was always going to come from the thread that had been dispatched to the ReadListener or WriteListener.

**Comment by sdeleuze** [comment] 2016-05-17 11:26
Fixed by https://github.com/spring-projects/spring-reactive/commit/0503d8dd49c6d9ea95eb1c026128d2fd9f884869, thanks @markt-asf !

**Closed by sdeleuze** 2016-05-17 11:26 UTC
